"""Default chat command profile and supported controller actions."""

from __future__ import annotations


SUPPORTED_ACTIONS = frozenset({
    "move_forward", "move_backward", "strafe_left", "strafe_right",
    "look_left", "look_right", "look_up", "look_down",
    "left_trigger", "right_trigger",
    "button_a", "button_b", "button_x", "button_y",
    "button_lb", "button_rb", "button_l3", "button_r3",
    "button_start", "button_back",
    "button_guide", "button_dpad_up", "button_dpad_down",
    "button_dpad_left", "button_dpad_right",
})


def _command(action: str, strength: float, duration_ms: int,
             *, allow_strength: bool = False, allow_duration: bool = True) -> dict:
    return {
        "action": action,
        "strength": strength,
        "duration_ms": duration_ms,
        "allow_strength_argument": allow_strength,
        "allow_duration_argument": allow_duration,
        "enabled": True,
    }


DEFAULT_COMMANDS = {
    # Movement (Left Analog Stick: accepts strength % and duration ms)
    "w": _command("move_forward", 1.0, 400, allow_strength=True, allow_duration=True),
    "forward": _command("move_forward", 1.0, 400, allow_strength=True, allow_duration=True),
    "s": _command("move_backward", 1.0, 400, allow_strength=True, allow_duration=True),
    "back": _command("move_backward", 1.0, 400, allow_strength=True, allow_duration=True),
    "backward": _command("move_backward", 1.0, 400, allow_strength=True, allow_duration=True),
    "a": _command("strafe_left", 1.0, 350, allow_strength=True, allow_duration=True),
    "d": _command("strafe_right", 1.0, 350, allow_strength=True, allow_duration=True),

    # Camera / Aiming (Right Analog Stick: accepts strength % and duration ms)
    "left": _command("look_left", 0.4, 150, allow_strength=True, allow_duration=True),
    "right": _command("look_right", 0.4, 150, allow_strength=True, allow_duration=True),
    "up": _command("look_up", 0.4, 150, allow_strength=True, allow_duration=True),
    "down": _command("look_down", 0.4, 150, allow_strength=True, allow_duration=True),

    # Triggers (accept strength % and duration ms)
    "fire": _command("right_trigger", 1.0, 180, allow_strength=True, allow_duration=True),
    "shoot": _command("right_trigger", 1.0, 180, allow_strength=True, allow_duration=True),
    "ads": _command("left_trigger", 1.0, 600, allow_strength=True, allow_duration=True),
    "aim": _command("left_trigger", 1.0, 600, allow_strength=True, allow_duration=True),

    # Face Buttons & Actions (accept custom duration ms)
    "jump": _command("button_a", 1.0, 120, allow_duration=True),
    "crouch": _command("button_b", 1.0, 120, allow_duration=True),
    "slide": _command("button_b", 1.0, 400, allow_duration=True),
    "b": _command("button_b", 1.0, 120, allow_duration=True),
    "reload": _command("button_x", 1.0, 120, allow_duration=True),
    "interact": _command("button_x", 1.0, 800, allow_duration=True),
    "use": _command("button_x", 1.0, 800, allow_duration=True),
    "buy": _command("button_x", 1.0, 800, allow_duration=True),
    "revive": _command("button_x", 1.0, 1500, allow_duration=True),
    "x": _command("button_x", 1.0, 300, allow_duration=True),
    "swap": _command("button_y", 1.0, 120, allow_duration=True),
    "switch": _command("button_y", 1.0, 120, allow_duration=True),
    "y": _command("button_y", 1.0, 120, allow_duration=True),
    "sprint": _command("button_l3", 1.0, 500, allow_duration=True),
    "melee": _command("button_r3", 1.0, 120, allow_duration=True),
    "knife": _command("button_r3", 1.0, 120, allow_duration=True),
    "tac": _command("button_lb", 1.0, 120, allow_duration=True),
    "tactical": _command("button_lb", 1.0, 120, allow_duration=True),
    "nade": _command("button_rb", 1.0, 120, allow_duration=True),
    "grenade": _command("button_rb", 1.0, 120, allow_duration=True),
    "menu": _command("button_start", 1.0, 120, allow_duration=True),
    "start": _command("button_start", 1.0, 120, allow_duration=True),
    "view": _command("button_back", 1.0, 120, allow_duration=True),
    "guide": _command("button_guide", 1.0, 120, allow_duration=True),
    "dpadup": _command("button_dpad_up", 1.0, 120, allow_duration=True),
    "dpaddown": _command("button_dpad_down", 1.0, 120, allow_duration=True),
    "dpadleft": _command("button_dpad_left", 1.0, 120, allow_duration=True),
    "dpadright": _command("button_dpad_right", 1.0, 120, allow_duration=True),
}


# Friendly one-token aliases for high-volume chat.  These intentionally keep
# the keyboard-like movement meanings of w/a/s/d and provide explicit names
# for face buttons so that "a" remains strafe-left rather than becoming
# ambiguous with the Xbox A button.
DEFAULT_COMMANDS.update({
    # Natural-language movement and aim aliases.
    "walk": DEFAULT_COMMANDS["forward"],
    "move": DEFAULT_COMMANDS["forward"],
    "advance": DEFAULT_COMMANDS["forward"],
    "fwd": DEFAULT_COMMANDS["forward"],
    "fw": DEFAULT_COMMANDS["forward"],
    "bk": DEFAULT_COMMANDS["back"],
    "bw": DEFAULT_COMMANDS["back"],
    "reverse": DEFAULT_COMMANDS["back"],
    "retreat": DEFAULT_COMMANDS["back"],
    "strafeleft": DEFAULT_COMMANDS["a"],
    "leftstrafe": DEFAULT_COMMANDS["a"],
    "lstrafe": DEFAULT_COMMANDS["a"],
    "straferight": DEFAULT_COMMANDS["d"],
    "rightstrafe": DEFAULT_COMMANDS["d"],
    "rstrafe": DEFAULT_COMMANDS["d"],
    "sl": DEFAULT_COMMANDS["slide"],
    "cr": DEFAULT_COMMANDS["crouch"],
    "duck": DEFAULT_COMMANDS["crouch"],
    "prone": DEFAULT_COMMANDS["crouch"],
    "j": DEFAULT_COMMANDS["jump"],
    "hop": DEFAULT_COMMANDS["jump"],
    "vault": DEFAULT_COMMANDS["jump"],
    "rl": DEFAULT_COMMANDS["reload"],
    "rel": DEFAULT_COMMANDS["reload"],
    "rld": DEFAULT_COMMANDS["reload"],
    "sw": DEFAULT_COMMANDS["swap"],
    "wpn": DEFAULT_COMMANDS["swap"],
    "weapon": DEFAULT_COMMANDS["swap"],
    "next": DEFAULT_COMMANDS["swap"],
    "sp": DEFAULT_COMMANDS["sprint"],
    "runfast": DEFAULT_COMMANDS["sprint"],
    "boost": DEFAULT_COMMANDS["sprint"],
    "m": DEFAULT_COMMANDS["melee"],
    "stab": DEFAULT_COMMANDS["melee"],
    "punch": DEFAULT_COMMANDS["melee"],
    "g": DEFAULT_COMMANDS["nade"],
    "gren": DEFAULT_COMMANDS["nade"],
    "frag": DEFAULT_COMMANDS["nade"],
    "lethal": DEFAULT_COMMANDS["nade"],
    "bomb": DEFAULT_COMMANDS["nade"],
    "t": DEFAULT_COMMANDS["tac"],
    "tacgren": DEFAULT_COMMANDS["tac"],
    "monkey": DEFAULT_COMMANDS["tac"],
    "i": DEFAULT_COMMANDS["interact"],
    "usex": DEFAULT_COMMANDS["interact"],
    "box": DEFAULT_COMMANDS["interact"],
    "door": DEFAULT_COMMANDS["interact"],
    "open": DEFAULT_COMMANDS["interact"],
    "action": DEFAULT_COMMANDS["interact"],
    "pick": DEFAULT_COMMANDS["interact"],
    "pickup": DEFAULT_COMMANDS["interact"],
    "pack": DEFAULT_COMMANDS["interact"],
    "pap": DEFAULT_COMMANDS["interact"],
    "mysterybox": DEFAULT_COMMANDS["interact"],
    "rev": DEFAULT_COMMANDS["revive"],
    "res": DEFAULT_COMMANDS["revive"],
    "save": DEFAULT_COMMANDS["revive"],
    "turnleft": DEFAULT_COMMANDS["left"],
    "turnright": DEFAULT_COMMANDS["right"],
    "turnl": DEFAULT_COMMANDS["left"],
    "turnr": DEFAULT_COMMANDS["right"],
    "lookleft": DEFAULT_COMMANDS["left"],
    "lookright": DEFAULT_COMMANDS["right"],
    "lookup": DEFAULT_COMMANDS["up"],
    "lookdown": DEFAULT_COMMANDS["down"],
    "u": DEFAULT_COMMANDS["up"],
    "dn": DEFAULT_COMMANDS["down"],
    "rsleft": DEFAULT_COMMANDS["left"],
    "rsright": DEFAULT_COMMANDS["right"],
    "rsup": DEFAULT_COMMANDS["up"],
    "rsdown": DEFAULT_COMMANDS["down"],
    "lsup": DEFAULT_COMMANDS["w"],
    "lsdown": DEFAULT_COMMANDS["s"],
    "lsleft": DEFAULT_COMMANDS["a"],
    "lsright": DEFAULT_COMMANDS["d"],
    "lt": DEFAULT_COMMANDS["ads"],
    "zoom": DEFAULT_COMMANDS["ads"],
    "aimdown": DEFAULT_COMMANDS["ads"],
    "rt": DEFAULT_COMMANDS["fire"],
    "f": DEFAULT_COMMANDS["fire"],
    "attack": DEFAULT_COMMANDS["fire"],
    "atk": DEFAULT_COMMANDS["fire"],
    "trigger": DEFAULT_COMMANDS["fire"],
    "lb": DEFAULT_COMMANDS["tac"],
    "rb": DEFAULT_COMMANDS["nade"],
    "l3": DEFAULT_COMMANDS["sprint"],
    "r3": DEFAULT_COMMANDS["melee"],
    "facea": DEFAULT_COMMANDS["jump"],
    "faceb": DEFAULT_COMMANDS["crouch"],
    "facex": DEFAULT_COMMANDS["x"],
    "facey": DEFAULT_COMMANDS["y"],
    "btn_a": DEFAULT_COMMANDS["jump"],
    "btn_b": DEFAULT_COMMANDS["crouch"],
    "btn_x": DEFAULT_COMMANDS["x"],
    "btn_y": DEFAULT_COMMANDS["y"],
    "buttona": DEFAULT_COMMANDS["jump"],
    "buttonb": DEFAULT_COMMANDS["crouch"],
    "buttonx": DEFAULT_COMMANDS["x"],
    "buttony": DEFAULT_COMMANDS["y"],
    "du": DEFAULT_COMMANDS["dpadup"],
    "dd": DEFAULT_COMMANDS["dpaddown"],
    "dl": DEFAULT_COMMANDS["dpadleft"],
    "dr": DEFAULT_COMMANDS["dpadright"],
    "updp": DEFAULT_COMMANDS["dpadup"],
    "downdp": DEFAULT_COMMANDS["dpaddown"],
    "leftdp": DEFAULT_COMMANDS["dpadleft"],
    "rightdp": DEFAULT_COMMANDS["dpadright"],
})


# A macro expands to independent leases, so every component is active at the
# same instant.  Modifiers following a macro apply to its first component;
# e.g. "run 80 1.2s" means "w 80 1.2s sprint".
COMBO_ALIASES: dict[str, tuple[str, ...]] = {
    "go": ("w", "sprint"),
    "run": ("w", "sprint"),
    "dash": ("w", "sprint"),
    "rush": ("w", "sprint"),
    "runfire": ("w", "sprint", "fire"),
    "runshoot": ("w", "sprint", "fire"),
    "runaim": ("w", "sprint", "ads"),
    "runaimfire": ("w", "sprint", "ads", "fire"),
    "combat": ("ads", "fire"),
    "fight": ("ads", "fire"),
    "aimfire": ("ads", "fire"),
    "shootaim": ("ads", "fire"),
    "jumpfire": ("jump", "fire"),
    "slidefire": ("w", "sprint", "slide", "fire"),
    "reloadmove": ("w", "reload"),
    "panic": ("w", "sprint", "fire"),
    "dodgeleft": ("a", "sprint"),
    "dodgeright": ("d", "sprint"),
    "slideleft": ("a", "sprint", "slide"),
    "slideright": ("d", "sprint", "slide"),
}
